[mgr]
append_keymap = [
  # Hopping
  { on = "<A-k>", run = "arrow prev", desc = "Previous file" },
  { on = "<A-j>", run = "arrow next", desc = "Next file" },
  # Navigation
  { on = "<A-h>", run = "leave", desc = "Back to the parent directory" },
  { on = "<A-l>", run = "enter", desc = "Enter the child directory" },
]

[[mgr.prepend_keymap]]
on = ["g", "w"]
run = 'shell --orphan -- ln -sfnT %h "$HOME/.wallpaper" && { pkill -x wbg; exec wbg -s "$HOME/.wallpaper"; }'
desc = "Set as wallpaper"
