# symlinked to /etc/tlp.d/01-tlp.conf

# Charging starts once the battery level is below this threshold.
START_CHARGE_THRESH_BAT0=55
# Charging stops when the battery level reaches or exceeds this threshold.
STOP_CHARGE_THRESH_BAT0=80

# Restore charge thresholds when AC is unplugged: 0=disable, 1=enable.
# Default: 1

RESTORE_THRESHOLDS_ON_BAT=1
