#!/bin/sh

# autostart
pkill sxhkd; sxhkd &
pkill polkit-gnome-au; /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pkill picom; picom &
pkill polybar; polybar -c ~/.config/polybar/config.ini main &
pkill greenclip; greenclip clear; greenclip daemon &
feh --no-fehbg --bg-fill $HOME/.config/wallpaper/wallpaper

# bspwm config
bspc monitor -d                     1 2 3 4 5
bspc config border_width	        2
bspc config window_gap		        6
bspc config normal_border_color     "#2E2E2E"
bspc config focused_border_color    "#A9B665"
bspc config presel_feedback_color   "#D4BE98"
bspc config swallow_first_click     false
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config swallow_first_click     false
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc rule -a pavucontrol state=floating
bspc rule -a Lxappearance state=floating